### ISSUE TITLE
Binary

### ISSUE THREAD

**Issue by sergeevabc** [cohadar/mkrandom#1]
Dear Damir, could you be so kind to compile .exe (preferably x64) for the rest of us?

**Comment by cohadar** [comment]
There are too many operating system/architecture combinations for me to bother.
It is really easy to do it yourself, check the readme.

**Comment by sergeevabc** [comment]
“Res of us” are merely users, not developers with GCC on board.
Binary for Windows 7 x64 would be enough, should be quite simple to compile.

**Comment by cohadar** [comment]
Ok, made some binaries, check the bin/ directory.

**Comment by sergeevabc** [comment]
Wow, it is so light on memory and lightning fast! Thanks, @cohadar 
Seems to be my favourite from now on (previous one is [dd for windows][1]).

[1]: http://www.chrysocome.net/dd
