### ISSUE TITLE
Randomness

### ISSUE THREAD

**Issue by sergeevabc** [cohadar/mkrandom#2]
Let’s generate two files of equal size.
```
mkrandom.exe 1g january
mkrandom.exe 1g february
```
And examine them closely.
```
0B 00 00 00 2B ...
0B 00 00 00 22 ...
```
First four bytes are the same, why?

**Comment by cohadar** [comment]
Because random seed is based on time and you ran mkrandom.exe twice in a row with small time pause. If you run it again now the number will be different.

**Comment by cohadar** [comment]
But yeah, this needs to be fixed.

**Comment by sergeevabc** [comment]
Readme.md refers to comparison of random number generators (PCG, the winner, is used within mkrandom.exe, right?), so full randomness was expected. Updated binary is ~74% larger, is it supposed to be this way?

**Comment by cohadar** [comment]
Yeah PCG is used.
Regarding file size: I used a different compiler (no particular reason why), it is irrelevant I think.

**Comment by sergeevabc** [comment]
[Tiny C Compiler][1] 0.9.26, which I’ve downloaded to try some magic of yours, produces 5120 bytes and it works.

**Comment by sergeevabc** [comment]
```
mkrandom 1g march
```
Stats by [Enc][1] and [Entropy][2].
```c
Entropy = 8.000000 bits per byte (8.0 = random) and could be further compressed by 0.0%
Number of bits set = (49.9999/50.0001)% (50/50 = random)
Bit Ratio = 0.99999485 (Ratio of 1.0 = random)
Arithmetic Mean Value = 127.499 (127.5 = random)
Monte Carlo estimate of Pi = 3.13255677 (0.29% error) (3.14159256 = random)
Serial correlation coefficient is 0.000037 (totally uncorrelated = 0.0).

Chi-Squared distribution = 263.282 (lower is more random),
and randomly would exceed this value 34.74 % of the times.
```
Visualization by [File2D][3].
[!][4]

[1]: http://www.fourmilab.ch/random/
[2]: https://github.com/0xBADCODE/entropy
[3]: http://gynvael.coldwind.pl/?id=199
[4]: https://i.imgur.com/Zr9OnEg.png
